---
name: 'Build forgejo_runner_container Image'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/oci-build-image.yml'     
    
jobs:
  build:
    name: 'OCI'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    with:
      registry: ghcr.io/di0ik
      image_name: forgejo_runner_container

